- name: Create rke user with a home directory
  ansible.builtin.user:
    name: rke
    create_home: yes
    
- name: Add rke user to docker group 
  ansible.builtin.user:
    name: rke
    groups: docker
    append: yes


- name: Create .ssh directory 
  ansible.builtin.file:
    path: /home/rke/.ssh
    state: directory
    mode: '0700'
    owner: rke
    group: rke 

- name: Copy authorized_keys
  ansible.builtin.copy:
    src:  ~/.ssh/id_rsa.pub
    dest: /home/rke/.ssh/authorized_keys
    owner: rke
    group: rke
    mode: '0600'

- name: Set ownership of /home/rke
  ansible.builtin.file:
    path: /home/rke
    owner: rke
    group: rke